# Run `docker compose up --build` using latest docker, then Ctrl-C to kill the running containers.
# -f for compose file spec.
# docker compose -f docker-compose.m1.yml up --build

version: "3.8"
services:

  stranasum-inference-server:
    build: 
      context: ./inference-server
      dockerfile: Dockerfile.cloud
    ports:
      - 8080:8080
      
  stranasum-frontend:
    build: ./stranasum-frontend
    ports:
      - 1234:1234
      
    
    